import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { MessageSquare, Sparkles, BarChart, Users, Brain, Clock } from 'lucide-react';
import Navbar from '@/components/Navbar';
import HeroSection from '@/components/HeroSection';
import FeatureCard from '@/components/FeatureCard';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

const Index = () => {
  const navigate = useNavigate();
  const [demoOpen, setDemoOpen] = useState(false);
  
  const features = [
    {
      icon: MessageSquare,
      title: 'AI-Driven Questions',
      description: 'Job-specific questions generated by AI to simulate real interviews.'
    },
    {
      icon: Sparkles,
      title: 'Real-time Feedback',
      description: 'Get instant analysis of your answers with actionable suggestions.'
    },
    {
      icon: BarChart,
      title: 'Performance Metrics',
      description: 'Track your progress with detailed scoring and analytics.'
    },
    {
      icon: Users,
      title: 'Industry Expertise',
      description: 'Questions tailored to specific industries and job roles.'
    },
    {
      icon: Brain,
      title: 'Sentiment Analysis',
      description: 'AI detects confidence levels, hesitation, and engagement.'
    },
    {
      icon: Clock,
      title: '24/7 Availability',
      description: 'Practice interviews anytime, anywhere, at your own pace.'
    }
  ];

  const testimonials = [
    {
      quote: "This tool helped me prepare for my tech interview. The AI feedback was surprisingly insightful.",
      author: "Sarah J.",
      role: "Software Engineer"
    },
    {
      quote: "I credit my job offer to the practice I got with this simulator. It identified weaknesses in my answers I wouldn't have caught.",
      author: "Michael T.",
      role: "Product Manager"
    },
    {
      quote: "The real-time feedback helped me refine my responses. I felt so much more confident in my actual interview.",
      author: "Rebecca L.",
      role: "UX Designer"
    }
  ];

  const handleStartInterview = () => {
    navigate('/setup');
  };

  const handleWatchDemo = () => {
    setDemoOpen(true);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      
      <HeroSection 
        onStartInterview={handleStartInterview}
        onWatchDemo={handleWatchDemo}
      />
      
      <section className="py-16 md:py-24 bg-white">
        <div className="container mx-auto px-4 sm:px-6 max-w-7xl">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-12">Features That Set Us Apart</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <FeatureCard
                key={index}
                icon={feature.icon}
                title={feature.title}
                description={feature.description}
              />
            ))}
          </div>
        </div>
      </section>
      
      <Dialog open={demoOpen} onOpenChange={setDemoOpen}>
        <DialogContent className="max-w-4xl w-full">
          <DialogHeader>
            <DialogTitle>Interview AI Demo</DialogTitle>
            <DialogDescription>
              Watch how our AI-powered interview platform works
            </DialogDescription>
          </DialogHeader>
          <div className="aspect-video w-full bg-gray-100 rounded-md flex items-center justify-center">
            <div className="text-center p-6">
              <p className="text-lg font-medium text-gray-800 mb-2">Demo Video</p>
              <p className="text-sm text-gray-600">
                This is a placeholder for the demo video. In a real application, an embedded video would be displayed here.
              </p>
            </div>
          </div>
        </DialogContent>
      </Dialog>
      
      <section className="py-16 bg-white">
        <div className="container px-4 sm:px-6 mx-auto max-w-7xl">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">What Our Users Say</h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Join thousands of job seekers who have improved their interview skills
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="glass-card">
                <div className="flex flex-col h-full">
                  <div className="flex-grow">
                    <p className="text-gray-600 italic mb-4">"{testimonial.quote}"</p>
                  </div>
                  <div className="mt-4 pt-4 border-t border-gray-100">
                    <p className="font-semibold text-gray-900">{testimonial.author}</p>
                    <p className="text-sm text-gray-500">{testimonial.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      <section className="py-16 bg-interview-blue">
        <div className="container px-4 sm:px-6 mx-auto max-w-7xl">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-white mb-6">Ready to Ace Your Next Interview?</h2>
            <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
              Start practicing today and gain the confidence to impress any interviewer.
            </p>
            <Link to="/setup">
              <Button className="bg-white text-interview-blue hover:bg-blue-50 font-medium px-8 py-3 rounded-lg shadow-button text-lg">
                Get Started Free
              </Button>
            </Link>
          </div>
        </div>
      </section>
      
      <footer className="bg-gray-900 text-white py-12">
        <div className="container px-4 sm:px-6 mx-auto max-w-7xl">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <h3 className="text-lg font-semibold mb-4">InterviewAI</h3>
              <p className="text-gray-400 text-sm">
                AI-powered interview preparation platform to help you land your dream job.
              </p>
            </div>
            <div>
              <h4 className="text-sm font-semibold uppercase text-gray-400 mb-4">Features</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">AI Interviews</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Feedback Analysis</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Resume Review</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Mock Interviews</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-sm font-semibold uppercase text-gray-400 mb-4">Resources</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Blog</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Interview Tips</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Career Advice</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Industry Guides</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-sm font-semibold uppercase text-gray-400 mb-4">Company</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">About Us</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Contact</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Privacy Policy</a></li>
                <li><a href="#" className="text-gray-300 hover:text-white transition-colors">Terms of Service</a></li>
              </ul>
            </div>
          </div>
          <div className="mt-8 pt-8 border-t border-gray-800 text-center">
            <p className="text-gray-400 text-sm">
              © {new Date().getFullYear()} InterviewAI. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Index;
