
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkznoustvwyiugxtvmmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrem5vdXN0dnd5aXVneHR2bW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODY4NjcsImV4cCI6MjA1NzQ2Mjg2N30.T82TlLiOiJiTiyOmBH8MrG7UQwqqeRwh9blQSBtkjzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
